title: "Ikenna — Senior Android Developer"
description: "Building secure, scalable mobile experiences"
# baseurl: "" 
# url: "https://ikenna-i.github.io/ikenna-portfolio"
baseurl: "/ikenna-portfolio"
url: "https://andy112.github.io"

# Theme
theme: minima

# Social links
github_username: ikenna-i
linkedin_username: your-linkedin-username
email: your-email@example.com

# Build settings
markdown: kramdown
