title: "Ikenna — Senior Android Developer"
description: "Building secure, scalable mobile experiences"
# baseurl: "" 
# url: "https://ikenna-i.github.io/ikenna-portfolio"
baseurl: "/ikenna-portfolio"
url: "https://andy112.github.io"

# Theme
theme: minima

author:
  name: "Ikenna Igboasoiyi"
  title: "Software Engineer"

# Social links
github_username: https://github.com/Andy112
linkedin_username: www.linkedin.com/in/ikenna-igboasoiyi
email: ikennaigboasoiyi@yahoo.com

# Build settings
markdown: kramdown
